# Generated by Django 5.1.2 on 2024-10-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramsales',
            name='state',
        ),
    ]
