# Generated by Django 5.1.2 on 2024-10-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramapp', '0002_remove_telegramsales_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSales',
        ),
    ]
