# Generated by Django 5.1.2 on 2024-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramapp', '0003_delete_telegramsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
