# Generated by Django 5.1.2 on 2024-10-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramapp', '0004_telegramsales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramSales',
        ),
    ]
