# Generated by Django 5.1.2 on 2024-10-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramapp', '0006_telegramsales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUsers',
        ),
    ]
